// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (thread_id, content) VALUES ($1, $2) RETURNING pk, id, thread_id, content, created_at
`

type CreateMessageParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	Content  string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ThreadID, arg.Content)
	var i Message
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.ThreadID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :one
DELETE FROM messages WHERE id = $1 RETURNING pk, id, thread_id, content, created_at
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, deleteMessage, id)
	var i Message
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.ThreadID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT pk, id, thread_id, content, created_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.ThreadID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByMessageId = `-- name: GetMessageByMessageId :one
SELECT pk, id, thread_id, content, created_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByMessageId(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByMessageId, id)
	var i Message
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.ThreadID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT pk, id, thread_id, content, created_at FROM messages WHERE id in ($1) ORDER BY id
`

func (q *Queries) GetMessages(ctx context.Context, id uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessages, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.ThreadID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByThreadId = `-- name: GetMessagesByThreadId :many
SELECT pk, id, thread_id, content, created_at FROM messages WHERE thread_id = $1 ORDER BY id
`

func (q *Queries) GetMessagesByThreadId(ctx context.Context, threadID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByThreadId, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.ThreadID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
