// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	Pk        int64              `json:"pk"`
	ID        uuid.UUID          `json:"id"`
	ThreadID  uuid.UUID          `json:"thread_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Thread struct {
	Pk        int64              `json:"pk"`
	ID        uuid.UUID          `json:"id"`
	Title     *string            `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
