// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	DeleteMessage(ctx context.Context, id uuid.UUID) (Message, error)
	DeleteThread(ctx context.Context, id uuid.UUID) (Thread, error)
	GetMessage(ctx context.Context, id uuid.UUID) (Message, error)
	GetMessageByMessageId(ctx context.Context, id uuid.UUID) (Message, error)
	GetMessages(ctx context.Context, id uuid.UUID) ([]Message, error)
	GetMessagesByThreadId(ctx context.Context, threadID uuid.UUID) ([]Message, error)
	GetThread(ctx context.Context, id uuid.UUID) (Thread, error)
	GetThreads(ctx context.Context, id uuid.UUID) ([]Thread, error)
}

var _ Querier = (*Queries)(nil)
