// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (title) VALUES ( $1) RETURNING pk, id, title, created_at
`

func (q *Queries) CreateThread(ctx context.Context, title *string) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, title)
	var i Thread
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :one
DELETE FROM threads WHERE id = $1 RETURNING pk, id, title, created_at
`

func (q *Queries) DeleteThread(ctx context.Context, id uuid.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, deleteThread, id)
	var i Thread
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadById = `-- name: GetThreadById :one
SELECT pk, id, title, created_at FROM threads WHERE id = $1
`

func (q *Queries) GetThreadById(ctx context.Context, id uuid.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadById, id)
	var i Thread
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}
