// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (id, title) VALUES ($1, $2)
RETURNING pk, id, title, created_at
`

type CreateThreadParams struct {
	ID    uuid.UUID   `json:"id"`
	Title pgtype.Text `json:"title"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, arg.ID, arg.Title)
	var i Thread
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :one
DELETE FROM threads WHERE id = $1 RETURNING pk, id, title, created_at
`

func (q *Queries) DeleteThread(ctx context.Context, id uuid.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, deleteThread, id)
	var i Thread
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT pk, id, title, created_at FROM threads WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getThreads = `-- name: GetThreads :many
SELECT pk, id, title, created_at FROM threads WHERE id in ($1) ORDER BY id
`

func (q *Queries) GetThreads(ctx context.Context, id uuid.UUID) ([]Thread, error) {
	rows, err := q.db.Query(ctx, getThreads, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
